server:
  port: 8081
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/suancaiyu?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&serverTimezone=GMT%2B8
      username: suancaiyu
      password: ikzE!2Qimc
      driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
        view:
          prefix: /WEB-INF/views
          suffix: .html
mybatis-plus:
    mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com.suancaiyu: debug # 或者使用trace来获取更详细的日志
    org.springframework: info
